package codemap

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const repoRoot = "../.."

func goKey(path string) ModuleKey { return ModuleKey{Path: path, Language: "go"} }

func TestDiscoverFiles_BasicGoProject(t *testing.T) {
	modules, err := DiscoverFiles(repoRoot, DiscoveryOpts{})
	require.NoError(t, err)
	assert.NotEmpty(t, modules, "expected at least one module in goYoke repo")

	// Verify well-known modules are present.
	_, hasValidate := modules[goKey("cmd/goyoke-validate")]
	_, hasArchive := modules[goKey("cmd/goyoke-archive")]
	assert.True(t, hasValidate, "expected cmd/goyoke-validate module")
	assert.True(t, hasArchive, "expected cmd/goyoke-archive module")

	// Every Go file should end in .go and not be a test file.
	for key, files := range modules {
		if key.Language != "go" {
			continue
		}
		for _, f := range files {
			assert.Equal(t, ".go", filepath.Ext(f), "module %v: non-.go file %s", key, f)
			assert.False(t, len(f) > 8 && f[len(f)-8:] == "_test.go",
				"module %v: test file %s should be excluded", key, f)
		}
	}
}

func TestDiscoverFiles_SkipsDefaultDirs(t *testing.T) {
	root := t.TempDir()
	createFile(t, filepath.Join(root, "vendor", "foo.go"), "package vendor\n")
	createFile(t, filepath.Join(root, "node_modules", "foo.go"), "package nm\n")
	createFile(t, filepath.Join(root, ".git", "foo.go"), "package git\n")
	createFile(t, filepath.Join(root, "testdata", "foo.go"), "package td\n")
	createFile(t, filepath.Join(root, "target", "foo.go"), "package target\n")
	createFile(t, filepath.Join(root, "real", "main.go"), "package real\n")

	modules, err := DiscoverFiles(root, DiscoveryOpts{})
	require.NoError(t, err)

	assert.Contains(t, modules, goKey("real"), "expected 'real' module")
	assert.NotContains(t, modules, goKey("vendor"))
	assert.NotContains(t, modules, goKey("node_modules"))
	assert.NotContains(t, modules, goKey(".git"))
	assert.NotContains(t, modules, goKey("testdata"))
	assert.NotContains(t, modules, goKey("target"))
}

func TestDiscoverFiles_RespectsGitignore(t *testing.T) {
	root := t.TempDir()
	createFile(t, filepath.Join(root, ".gitignore"), "ignored/\n")
	createFile(t, filepath.Join(root, "ignored", "main.go"), "package ignored\n")
	createFile(t, filepath.Join(root, "included", "main.go"), "package included\n")

	modules, err := DiscoverFiles(root, DiscoveryOpts{})
	require.NoError(t, err)

	assert.Contains(t, modules, goKey("included"))
	assert.NotContains(t, modules, goKey("ignored"))
}

func TestDiscoverFiles_SpecificFiles(t *testing.T) {
	root := t.TempDir()
	a := filepath.Join(root, "pkg", "a.go")
	b := filepath.Join(root, "pkg", "b.go")
	c := filepath.Join(root, "pkg", "c.go")
	createFile(t, a, "package pkg\n")
	createFile(t, b, "package pkg\n")
	createFile(t, c, "package pkg\n")

	modules, err := DiscoverFiles(root, DiscoveryOpts{SpecificFiles: []string{a, b}})
	require.NoError(t, err)

	files := modules[goKey("pkg")]
	require.Len(t, files, 2)

	names := []string{filepath.Base(files[0]), filepath.Base(files[1])}
	assert.ElementsMatch(t, names, []string{"a.go", "b.go"})
}

func TestDiscoverFiles_GeneratedDetection(t *testing.T) {
	root := t.TempDir()
	genFile := filepath.Join(root, "pkg", "gen.go")
	realFile := filepath.Join(root, "pkg", "real.go")
	createFile(t, genFile, "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pkg\n")
	createFile(t, realFile, "package pkg\n")

	// Default: generated files excluded.
	modules, err := DiscoverFiles(root, DiscoveryOpts{})
	require.NoError(t, err)
	files := modules[goKey("pkg")]
	require.Len(t, files, 1)
	assert.Equal(t, "pkg/real.go", files[0])
}

func TestDiscoverFiles_IncludeGenerated(t *testing.T) {
	root := t.TempDir()
	genFile := filepath.Join(root, "pkg", "gen.go")
	realFile := filepath.Join(root, "pkg", "real.go")
	createFile(t, genFile, "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pkg\n")
	createFile(t, realFile, "package pkg\n")

	modules, err := DiscoverFiles(root, DiscoveryOpts{IncludeGenerated: true})
	require.NoError(t, err)
	assert.Len(t, modules[goKey("pkg")], 2)
}

func TestDiscoverFiles_ExcludePatterns(t *testing.T) {
	root := t.TempDir()
	createFile(t, filepath.Join(root, "pkg", "keep.go"), "package pkg\n")
	createFile(t, filepath.Join(root, "pkg", "drop.go"), "package pkg\n")

	modules, err := DiscoverFiles(root, DiscoveryOpts{ExcludePatterns: []string{"drop.go"}})
	require.NoError(t, err)

	files := modules[goKey("pkg")]
	require.Len(t, files, 1)
	assert.Equal(t, "pkg/keep.go", files[0])
}

func TestDiscoverFiles_MultiLanguage(t *testing.T) {
	root := t.TempDir()
	createFile(t, filepath.Join(root, "src", "main.go"), "package main\n")
	createFile(t, filepath.Join(root, "src", "lib.py"), "def hello(): pass\n")
	createFile(t, filepath.Join(root, "src", "app.ts"), "export const x = 1;\n")
	createFile(t, filepath.Join(root, "src", "module.rs"), "pub fn foo() {}\n")

	modules, err := DiscoverFiles(root, DiscoveryOpts{})
	require.NoError(t, err)

	assert.Contains(t, modules, ModuleKey{Path: "src", Language: "go"})
	assert.Contains(t, modules, ModuleKey{Path: "src", Language: "python"})
	assert.Contains(t, modules, ModuleKey{Path: "src", Language: "typescript"})
	assert.Contains(t, modules, ModuleKey{Path: "src", Language: "rust"})
}

func TestDiscoverFiles_LangFilter(t *testing.T) {
	root := t.TempDir()
	createFile(t, filepath.Join(root, "src", "main.go"), "package main\n")
	createFile(t, filepath.Join(root, "src", "lib.py"), "def hello(): pass\n")

	modules, err := DiscoverFiles(root, DiscoveryOpts{Lang: "go"})
	require.NoError(t, err)

	assert.Contains(t, modules, ModuleKey{Path: "src", Language: "go"})
	assert.NotContains(t, modules, ModuleKey{Path: "src", Language: "python"})
}

func TestModuleToFilename(t *testing.T) {
	tests := []struct {
		module   string
		expected string
	}{
		{"cmd/goyoke-validate", "cmd--goyoke-validate"},
		{"internal/codemap", "internal--codemap"},
		{"pkg/routing", "pkg--routing"},
		{"", "_root"},
		{"single", "single"},
		{"a/b/c", "a--b--c"},
	}
	for _, tc := range tests {
		t.Run(tc.module, func(t *testing.T) {
			assert.Equal(t, tc.expected, moduleToFilename(tc.module))
		})
	}
}

func TestResolveProjectModule(t *testing.T) {
	mod, err := ResolveProjectModule(repoRoot)
	require.NoError(t, err)
	assert.Equal(t, "github.com/Bucket-Chemist/goYoke", mod)
}

func TestResolveProjectModule_MissingGoMod(t *testing.T) {
	_, err := ResolveProjectModule(t.TempDir())
	assert.Error(t, err)
}

func TestDetectLanguage(t *testing.T) {
	assert.Equal(t, "go", DetectLanguage("main.go"))
	assert.Equal(t, "go", DetectLanguage("/some/path/file.go"))
	assert.Equal(t, "python", DetectLanguage("script.py"))
	assert.Equal(t, "rust", DetectLanguage("lib.rs"))
	assert.Equal(t, "typescript", DetectLanguage("app.ts"))
	assert.Equal(t, "typescript", DetectLanguage("component.tsx"))
	assert.Equal(t, "r", DetectLanguage("analysis.R"))
	assert.Equal(t, "r", DetectLanguage("analysis.r"))
	assert.Equal(t, "unknown", DetectLanguage("file.txt"))
}

func TestDiscoverFiles_ExitNonexistentRoot(t *testing.T) {
	_, err := DiscoverFiles("/this/does/not/exist", DiscoveryOpts{})
	assert.Error(t, err)
}

// createFile writes content to path, creating parent dirs as needed.
func createFile(t *testing.T, path, content string) {
	t.Helper()
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
}

// --- extractNameFromTOML ---

func TestExtractNameFromTOML(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{"cargo style", "[package]\nname = \"my-crate\"\nversion = \"0.1.0\"\n", "my-crate"},
		{"pyproject style", "[tool.poetry]\nname = \"my-package\"\n", "my-package"},
		{"single quotes", "name = 'my-lib'\n", "my-lib"},
		{"no name field", "[package]\nversion = \"0.1.0\"\n", ""},
		{"empty input", "", ""},
		{"name with spaces around equals", "name  =  \"spaced\"\n", "spaced"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.expected, extractNameFromTOML([]byte(tc.input)))
		})
	}
}

// --- resolveRustProjectName ---

func TestResolveRustProjectName_Found(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "Cargo.toml"), "[package]\nname = \"my-crate\"\nversion = \"0.1.0\"\n")

	name, err := resolveRustProjectName(dir)
	require.NoError(t, err)
	assert.Equal(t, "my-crate", name)
}

func TestResolveRustProjectName_Missing(t *testing.T) {
	_, err := resolveRustProjectName(t.TempDir())
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "Cargo.toml")
}

func TestResolveRustProjectName_NoName(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "Cargo.toml"), "[package]\nversion = \"0.1.0\"\n")

	_, err := resolveRustProjectName(dir)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "name not found")
}

// --- resolveTypeScriptProjectName ---

func TestResolveTypeScriptProjectName_Found(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "package.json"), `{"name":"my-app","version":"1.0.0"}`)

	name, err := resolveTypeScriptProjectName(dir)
	require.NoError(t, err)
	assert.Equal(t, "my-app", name)
}

func TestResolveTypeScriptProjectName_Missing(t *testing.T) {
	_, err := resolveTypeScriptProjectName(t.TempDir())
	assert.Error(t, err)
}

func TestResolveTypeScriptProjectName_EmptyName(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "package.json"), `{"version":"1.0.0"}`)

	_, err := resolveTypeScriptProjectName(dir)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "name not found")
}

func TestResolveTypeScriptProjectName_InvalidJSON(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "package.json"), `{not json}`)

	_, err := resolveTypeScriptProjectName(dir)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "parse package.json")
}

// --- resolvePythonProjectName ---

func TestResolvePythonProjectName_Pyproject(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "pyproject.toml"), "[tool.poetry]\nname = \"my-python-pkg\"\n")

	name, err := resolvePythonProjectName(dir)
	require.NoError(t, err)
	assert.Equal(t, "my-python-pkg", name)
}

func TestResolvePythonProjectName_SetupCfg(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "setup.cfg"), "[metadata]\nname = \"setup-pkg\"\n")

	name, err := resolvePythonProjectName(dir)
	require.NoError(t, err)
	assert.Equal(t, "setup-pkg", name)
}

func TestResolvePythonProjectName_NotFound(t *testing.T) {
	_, err := resolvePythonProjectName(t.TempDir())
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "project name not found")
}

// --- resolveRProjectName ---

func TestResolveRProjectName_Found(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "DESCRIPTION"), "Package: myRPkg\nTitle: My R Package\n")

	name, err := resolveRProjectName(dir)
	require.NoError(t, err)
	assert.Equal(t, "myRPkg", name)
}

func TestResolveRProjectName_MissingFile(t *testing.T) {
	_, err := resolveRProjectName(t.TempDir())
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "DESCRIPTION")
}

func TestResolveRProjectName_MissingPackageField(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "DESCRIPTION"), "Title: My Package\nVersion: 0.1\n")

	_, err := resolveRProjectName(dir)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "Package field not found")
}

// --- ResolveProjectName ---

func TestResolveProjectName_Go(t *testing.T) {
	name, err := ResolveProjectName(repoRoot, "go")
	require.NoError(t, err)
	assert.Contains(t, name, "goYoke")
}

func TestResolveProjectName_Rust(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "Cargo.toml"), "[package]\nname = \"rust-proj\"\n")

	name, err := ResolveProjectName(dir, "rust")
	require.NoError(t, err)
	assert.Equal(t, "rust-proj", name)
}

func TestResolveProjectName_TypeScript(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "package.json"), `{"name":"ts-proj"}`)

	name, err := ResolveProjectName(dir, "typescript")
	require.NoError(t, err)
	assert.Equal(t, "ts-proj", name)
}

func TestResolveProjectName_Python(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "pyproject.toml"), "[project]\nname = \"py-proj\"\n")

	name, err := ResolveProjectName(dir, "python")
	require.NoError(t, err)
	assert.Equal(t, "py-proj", name)
}

func TestResolveProjectName_R(t *testing.T) {
	dir := t.TempDir()
	createFile(t, filepath.Join(dir, "DESCRIPTION"), "Package: RPkg\n")

	name, err := ResolveProjectName(dir, "r")
	require.NoError(t, err)
	assert.Equal(t, "RPkg", name)
}

func TestResolveProjectName_Unsupported(t *testing.T) {
	_, err := ResolveProjectName(t.TempDir(), "cobol")
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "unsupported language")
}
