package codemap

import (
	"encoding/json"
	"fmt"
	"strings"
)

// buildEnrichmentPrompt constructs the LLM prompt for enriching a single module.
func buildEnrichmentPrompt(modulePath string, symbols []Symbol, imports ImportGraph) string {
	var sb strings.Builder

	sb.WriteString("You are a code analysis assistant. Analyze the following Go module and provide structured enrichment data.\n\n")
	fmt.Fprintf(&sb, "## Module: %s\n\n", modulePath)

	if len(imports.Internal) > 0 {
		sb.WriteString("### Internal imports:\n")
		for _, imp := range imports.Internal {
			fmt.Fprintf(&sb, "- %s\n", imp)
		}
		sb.WriteString("\n")
	}
	if len(imports.External) > 0 {
		sb.WriteString("### External imports:\n")
		for _, imp := range imports.External {
			fmt.Fprintf(&sb, "- %s\n", imp)
		}
		sb.WriteString("\n")
	}

	sb.WriteString("### Symbols:\n\n")
	for _, sym := range symbols {
		fmt.Fprintf(&sb, "- **%s** (%s) lines %d-%d", sym.Name, sym.Kind, sym.LineStart, sym.LineEnd)
		if sym.Signature != "" {
			fmt.Fprintf(&sb, ": `%s`", sym.Signature)
		}
		sb.WriteString("\n")
	}

	sb.WriteString(`
## Task

Return a single JSON object (no markdown fences) with this exact structure:

{
  "module_description": "1-3 sentence description of this module's purpose and responsibilities",
  "module_category": "<one of: command, library, internal, test, config, documentation>",
  "key_types": ["up to 5 most important type names"],
  "key_functions": ["up to 5 most important function names"],
  "symbols": [
    {
      "name": "<symbol name>",
      "description": "1-2 sentence description of what this symbol does",
      "module_identity": "<one of: core, helper, glue, config, test, generated>",
      "complexity": "<one of: low, medium, high>",
      "is_entrypoint": <true|false>,
      "architectural_role": "<one of: handler, service, repository, middleware, utility, model, factory, orchestrator, validator, none>",
      "tags": ["cross-cutting concern tags like: concurrency, io, serialization, auth, etc."]
    }
  ]
}

Enum reference:
- module_category: command (main binary), library (shared pkg), internal (private pkg), test, config, documentation
- module_identity: core (primary logic), helper (utility, not meaningful alone), glue (adapter/wrapper), config (constants/defaults), test, generated
- complexity: low (<10 lines, linear), medium (10-50 lines, branching), high (>50 lines, complex state/concurrency)
- architectural_role: handler, service, repository, middleware, utility, model, factory, orchestrator, validator, none

Include an entry for EVERY symbol listed above. Return only the JSON object.
`)

	return sb.String()
}

// buildNarrativePrompt constructs the LLM prompt for generating ARCHITECTURE.md.
func buildNarrativePrompt(graph *Graph, enrichedModules map[string]*EnrichedModule) string {
	var sb strings.Builder

	sb.WriteString("You are a technical documentation writer. Generate an ARCHITECTURE.md file for this codebase.\n\n")
	fmt.Fprintf(&sb, "## Repository: %s\n\n", graph.Repo)
	fmt.Fprintf(&sb, "Stats: %d modules, %d symbols, %d dependency edges\n\n",
		graph.Stats.TotalModules, graph.Stats.TotalSymbols, graph.Stats.TotalDependencyEdges)

	sb.WriteString("## Module Summaries\n\n")
	for _, node := range graph.Layers.ModuleDependencies.Nodes {
		em, ok := enrichedModules[node.ID]
		desc := "(no description)"
		cat := node.Category
		if ok {
			if em.ModuleDescription != "" {
				desc = em.ModuleDescription
			}
			if em.ModuleCategory != "" {
				cat = em.ModuleCategory
			}
		}
		fmt.Fprintf(&sb, "### %s\n- Category: %s\n- Symbols: %d\n- Description: %s\n",
			node.ID, cat, node.SymbolCount, desc)
		if ok && len(em.KeyTypes) > 0 {
			fmt.Fprintf(&sb, "- Key types: %s\n", strings.Join(em.KeyTypes, ", "))
		}
		if ok && len(em.KeyFunctions) > 0 {
			fmt.Fprintf(&sb, "- Key functions: %s\n", strings.Join(em.KeyFunctions, ", "))
		}
		sb.WriteString("\n")
	}

	if len(graph.Layers.ModuleDependencies.Edges) > 0 {
		sb.WriteString("## Dependency Edges\n\n")
		for _, edge := range graph.Layers.ModuleDependencies.Edges {
			fmt.Fprintf(&sb, "- %s → %s\n", edge.From, edge.To)
		}
		sb.WriteString("\n")
	}

	sb.WriteString(`## Output Format

Generate a markdown ARCHITECTURE.md following this template structure:

# {repo_name} Architecture

> Auto-generated by /codebase-map
> {file_count} files across {module_count} modules

## Overview

{2-3 paragraph overview of the system's purpose and architecture}

## Module Dependency Graph

{describe the key dependency relationships in prose, referencing specific modules}

## Module Details

{for each significant module, a section with:
### module/path
**Category**: ...
**Purpose**: ...
**Key types**: ...
**Key functions**: ...
}

## Cross-Module Dependencies

{table or prose describing which modules depend on which}

## Statistics

| Metric | Value |
|--------|-------|
| Total modules | N |
| Total symbols | N |
| Total dependency edges | N |

Write the full ARCHITECTURE.md now. Return only the markdown content.
`)

	return sb.String()
}

// parseEnrichmentResponse extracts enrichmentResponse from LLM output text.
// Handles optional markdown code fences.
func parseEnrichmentResponse(text string) (*enrichmentResponse, error) {
	text = strings.TrimSpace(text)

	// Strip markdown code fences if present
	if strings.HasPrefix(text, "```") {
		lines := strings.SplitN(text, "\n", 2)
		if len(lines) == 2 {
			text = lines[1]
		}
		if idx := strings.LastIndex(text, "```"); idx >= 0 {
			text = text[:idx]
		}
		text = strings.TrimSpace(text)
	}

	// Find first { and last } to isolate JSON object
	start := strings.Index(text, "{")
	end := strings.LastIndex(text, "}")
	if start < 0 || end < 0 || end <= start {
		return nil, fmt.Errorf("no JSON object found in response (length %d)", len(text))
	}
	text = text[start : end+1]

	var resp enrichmentResponse
	if err := json.Unmarshal([]byte(text), &resp); err != nil {
		return nil, fmt.Errorf("parse enrichment JSON: %w", err)
	}
	return &resp, nil
}
