
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"reflect"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/Bucket-Chemist/GOgent-Fortress/test/integration"


)

var tests = []testing.InternalTest{

	{"TestComplexityRoutingWorkflow", _test.TestComplexityRoutingWorkflow},

	{"TestComplexityRoutingStaleMetrics", _test.TestComplexityRoutingStaleMetrics},

	{"TestEndToEnd_FullMLPipeline", _test.TestEndToEnd_FullMLPipeline},

	{"TestEndToEnd_SessionStartToValidate", _test.TestEndToEnd_SessionStartToValidate},

	{"TestEndToEnd_SubagentStopToArchive", _test.TestEndToEnd_SubagentStopToArchive},

	{"TestEndToEnd_ValidationToSharpEdge", _test.TestEndToEnd_ValidationToSharpEdge},

	{"TestEndToEnd_SessionArchivalWorkflow", _test.TestEndToEnd_SessionArchivalWorkflow},

	{"TestEndToEnd_MultiSessionHandoff", _test.TestEndToEnd_MultiSessionHandoff},

	{"TestNewTestHarness", _test.TestNewTestHarness},

	{"TestNewTestHarness_MissingFile", _test.TestNewTestHarness_MissingFile},

	{"TestLoadCorpus", _test.TestLoadCorpus},

	{"TestLoadCorpus_EmptyFile", _test.TestLoadCorpus_EmptyFile},

	{"TestLoadCorpus_MalformedJSON", _test.TestLoadCorpus_MalformedJSON},

	{"TestLoadCorpus_BlankLines", _test.TestLoadCorpus_BlankLines},

	{"TestLoadCorpus_MLTelemetryFields", _test.TestLoadCorpus_MLTelemetryFields},

	{"TestFilterEvents", _test.TestFilterEvents},

	{"TestFilterEvents_NoMatches", _test.TestFilterEvents_NoMatches},

	{"TestCompareResults", _test.TestCompareResults},

	{"TestCompareResults_ExitCodeDifference", _test.TestCompareResults_ExitCodeDifference},

	{"TestCompareResults_ReasonDifference", _test.TestCompareResults_ReasonDifference},

	{"TestCompareMLFields", _test.TestCompareMLFields},

	{"TestCompareMLFields_TimingTolerance", _test.TestCompareMLFields_TimingTolerance},

	{"TestCompareMLFields_SmallDurations", _test.TestCompareMLFields_SmallDurations},

	{"TestCompareMLFields_EmptyStringHandling", _test.TestCompareMLFields_EmptyStringHandling},

	{"TestCompareMLFields_AllFields", _test.TestCompareMLFields_AllFields},

	{"TestPrintSummary_EmptyResults", _test.TestPrintSummary_EmptyResults},

	{"TestPrintSummary_MixedResults", _test.TestPrintSummary_MixedResults},

	{"TestRunHook_RawJSONPreservation", _test.TestRunHook_RawJSONPreservation},

	{"TestRunHook_Success", _test.TestRunHook_Success},

	{"TestRunHook_NonZeroExit", _test.TestRunHook_NonZeroExit},

	{"TestRunHook_InvalidJSON", _test.TestRunHook_InvalidJSON},

	{"TestRunHook_MissingBinary", _test.TestRunHook_MissingBinary},

	{"TestRunHookBatch_Success", _test.TestRunHookBatch_Success},

	{"TestRunHookBatch_MissingBinary", _test.TestRunHookBatch_MissingBinary},

	{"TestRunHookBatch_NoMatchingEvents", _test.TestRunHookBatch_NoMatchingEvents},

	{"TestHookWorkflow_FullPipeline", _test.TestHookWorkflow_FullPipeline},

	{"TestHookWorkflow_ErrorHandling", _test.TestHookWorkflow_ErrorHandling},

	{"TestHookWorkflow_RealWorldScenario", _test.TestHookWorkflow_RealWorldScenario},

	{"TestMetricsParity_ToolCalls", _test.TestMetricsParity_ToolCalls},

	{"TestMetricsParity_ErrorLog", _test.TestMetricsParity_ErrorLog},

	{"TestMetricsParity_Violations", _test.TestMetricsParity_Violations},

	{"TestMLTelemetry_RoutingDecisionCapture", _test.TestMLTelemetry_RoutingDecisionCapture},

	{"TestMLTelemetry_DecisionUpdates", _test.TestMLTelemetry_DecisionUpdates},

	{"TestMLTelemetry_ConcurrentWrites", _test.TestMLTelemetry_ConcurrentWrites},

	{"TestMLTelemetry_CollaborationTracking", _test.TestMLTelemetry_CollaborationTracking},

	{"TestMLTelemetry_ExportReconciliation", _test.TestMLTelemetry_ExportReconciliation},

	{"TestMLTelemetry_RaceConditionDetection", _test.TestMLTelemetry_RaceConditionDetection},

	{"TestMLTelemetry_SequenceIntegrity", _test.TestMLTelemetry_SequenceIntegrity},

	{"TestOverrideWorkflow", _test.TestOverrideWorkflow},

	{"TestSessionArchive_Integration", _test.TestSessionArchive_Integration},

	{"TestSessionArchive_MetricsCollection", _test.TestSessionArchive_MetricsCollection},

	{"TestSessionArchive_FileArchival", _test.TestSessionArchive_FileArchival},

	{"TestSessionEndHook_EndToEnd", _test.TestSessionEndHook_EndToEnd},

	{"TestSessionEndHook_ErrorHandling", _test.TestSessionEndHook_ErrorHandling},

	{"TestSessionHandoffIntegration_FullWorkflow", _test.TestSessionHandoffIntegration_FullWorkflow},

	{"TestSessionHandoffIntegration_MinimalSession", _test.TestSessionHandoffIntegration_MinimalSession},

	{"TestSessionHandoffIntegration_ArtifactArchival", _test.TestSessionHandoffIntegration_ArtifactArchival},

	{"TestCLI_WorkingDirectoryBehavior", _test.TestCLI_WorkingDirectoryBehavior},

	{"TestCLI_EnvironmentVariables", _test.TestCLI_EnvironmentVariables},

	{"TestCLI_InvalidJSONInput", _test.TestCLI_InvalidJSONInput},

	{"TestCLI_StdinTimeout", _test.TestCLI_StdinTimeout},

	{"TestCLI_VersionFlag", _test.TestCLI_VersionFlag},

	{"TestCLI_HelpFlag", _test.TestCLI_HelpFlag},

	{"TestCLI_ExitCodes", _test.TestCLI_ExitCodes},

	{"TestCLI_ConfirmationJSONSchema", _test.TestCLI_ConfirmationJSONSchema},

	{"TestCLI_ShowSubcommand", _test.TestCLI_ShowSubcommand},

	{"TestCLI_StatsSubcommand", _test.TestCLI_StatsSubcommand},

	{"TestCLI_ListWithFilters", _test.TestCLI_ListWithFilters},

	{"TestSessionStart_Integration", _test.TestSessionStart_Integration},

	{"TestSessionStart_LanguageDetection", _test.TestSessionStart_LanguageDetection},

	{"TestSessionStart_ConventionLoading", _test.TestSessionStart_ConventionLoading},

	{"TestSessionStart_HandoffInjection", _test.TestSessionStart_HandoffInjection},

	{"TestSessionStart_RoutingSchemaLoad", _test.TestSessionStart_RoutingSchemaLoad},

	{"TestSessionStart_ErrorRecovery", _test.TestSessionStart_ErrorRecovery},

	{"TestStorage_ConcurrentWrites", _test.TestStorage_ConcurrentWrites},

	{"TestStorage_ConcurrentReadWrite", _test.TestStorage_ConcurrentReadWrite},

	{"TestStorage_LargeLogFile", _test.TestStorage_LargeLogFile},

	{"TestStorage_LogRotation", _test.TestStorage_LogRotation},

	{"TestStorage_AtomicAppend", _test.TestStorage_AtomicAppend},

	{"TestStorage_ConcurrentClear", _test.TestStorage_ConcurrentClear},

	{"TestStorage_ConcurrentCompositeKeys", _test.TestStorage_ConcurrentCompositeKeys},

	{"TestStorage_FileCorruption", _test.TestStorage_FileCorruption},

	{"TestStorage_RapidSuccessiveWrites", _test.TestStorage_RapidSuccessiveWrites},

	{"TestStorage_LineIntegrity", _test.TestStorage_LineIntegrity},

	{"TestEdgeCase_MalformedJSON_Input", _test.TestEdgeCase_MalformedJSON_Input},

	{"TestEdgeCase_EmptyInput", _test.TestEdgeCase_EmptyInput},

	{"TestEdgeCase_PartialJSON", _test.TestEdgeCase_PartialJSON},

	{"TestEdgeCase_ExtremelyLongErrorMessage", _test.TestEdgeCase_ExtremelyLongErrorMessage},

	{"TestEdgeCase_UnicodeInFilePath", _test.TestEdgeCase_UnicodeInFilePath},

	{"TestEdgeCase_SpecialCharsInError", _test.TestEdgeCase_SpecialCharsInError},

	{"TestEdgeCase_VeryOldTimestamp", _test.TestEdgeCase_VeryOldTimestamp},

	{"TestEdgeCase_FutureTimestamp", _test.TestEdgeCase_FutureTimestamp},

	{"TestEdgeCase_ZeroExitCode", _test.TestEdgeCase_ZeroExitCode},

	{"TestEdgeCase_NegativeExitCode", _test.TestEdgeCase_NegativeExitCode},

	{"TestEdgeCase_MultipleErrorTypesInOutput", _test.TestEdgeCase_MultipleErrorTypesInOutput},

	{"TestEdgeCase_EmptyFilePath", _test.TestEdgeCase_EmptyFilePath},

	{"TestEdgeCase_ComplexCommandParsing", _test.TestEdgeCase_ComplexCommandParsing},

	{"TestEdgeCase_MixedCaseErrorKeywords", _test.TestEdgeCase_MixedCaseErrorKeywords},

	{"TestEdgeCase_ResponseFieldVariations", _test.TestEdgeCase_ResponseFieldVariations},

	{"TestFallback_MissingProjectDir", _test.TestFallback_MissingProjectDir},

	{"TestFallback_NonExistentDir", _test.TestFallback_NonExistentDir},

	{"TestFallback_ReadOnlyDir", _test.TestFallback_ReadOnlyDir},

	{"TestFallback_CorruptedTrackerLog", _test.TestFallback_CorruptedTrackerLog},

	{"TestFallback_MissingTrackerLog", _test.TestFallback_MissingTrackerLog},

	{"TestFallback_EmptyTrackerLog", _test.TestFallback_EmptyTrackerLog},

	{"TestFallback_PartiallyWrittenEntry", _test.TestFallback_PartiallyWrittenEntry},

	{"TestFallback_InvalidEnvironmentVariables", _test.TestFallback_InvalidEnvironmentVariables},

	{"TestFallback_LongFilePath", _test.TestFallback_LongFilePath},

	{"TestFallback_FilePermissionChange", _test.TestFallback_FilePermissionChange},

	{"TestFallback_BrokenSymlink", _test.TestFallback_BrokenSymlink},

	{"TestFallback_ConcurrentDirectoryCreation", _test.TestFallback_ConcurrentDirectoryCreation},

	{"TestFallback_JSONMarshalError", _test.TestFallback_JSONMarshalError},

	{"TestSchema_SharpEdge_RequiredFields", _test.TestSchema_SharpEdge_RequiredFields},

	{"TestSchema_SharpEdge_TimestampFormat", _test.TestSchema_SharpEdge_TimestampFormat},

	{"TestSchema_SharpEdge_ConsecutiveFailuresMin", _test.TestSchema_SharpEdge_ConsecutiveFailuresMin},

	{"TestSchema_ValidateSharpEdge_Valid", _test.TestSchema_ValidateSharpEdge_Valid},

	{"TestSchema_ValidateSharpEdge_Invalid", _test.TestSchema_ValidateSharpEdge_Invalid},

	{"TestSchema_FailureInfo_Compatibility", _test.TestSchema_FailureInfo_Compatibility},

	{"TestSchema_JSONL_Format", _test.TestSchema_JSONL_Format},

	{"TestSchema_FieldNaming", _test.TestSchema_FieldNaming},

	{"TestWorkflow_SingleFailure_PassThrough", _test.TestWorkflow_SingleFailure_PassThrough},

	{"TestWorkflow_TwoFailures_Warning", _test.TestWorkflow_TwoFailures_Warning},

	{"TestWorkflow_ThreeFailures_Block", _test.TestWorkflow_ThreeFailures_Block},

	{"TestWorkflow_MultipleFiles_Independent", _test.TestWorkflow_MultipleFiles_Independent},

	{"TestWorkflow_MixedErrors_NoFalsePositive", _test.TestWorkflow_MixedErrors_NoFalsePositive},

	{"TestWorkflow_SameError_Trigger", _test.TestWorkflow_SameError_Trigger},

	{"TestWorkflow_CaptureToPendingLearnings", _test.TestWorkflow_CaptureToPendingLearnings},

	{"TestWorkflow_TimeWindowFiltering", _test.TestWorkflow_TimeWindowFiltering},

	{"TestWorkflow_ClearAfterResolution", _test.TestWorkflow_ClearAfterResolution},

	{"TestSharpEdge_Integration", _test.TestSharpEdge_Integration},

	{"TestSharpEdge_FailureDetection", _test.TestSharpEdge_FailureDetection},

	{"TestSharpEdge_SlidingWindow", _test.TestSharpEdge_SlidingWindow},

	{"TestSharpEdge_PerFileTracking", _test.TestSharpEdge_PerFileTracking},

	{"TestSharpEdge_MLTelemetryFields", _test.TestSharpEdge_MLTelemetryFields},

	{"TestSharpEdge_DecisionCorrelation", _test.TestSharpEdge_DecisionCorrelation},

	{"TestSubagentStop_Integration", _test.TestSubagentStop_Integration},

	{"TestSubagentStop_MLOutcomeLogging", _test.TestSubagentStop_MLOutcomeLogging},

	{"TestSubagentStop_CollaborationUpdates", _test.TestSubagentStop_CollaborationUpdates},

	{"TestSubagentStop_DecisionCorrelation", _test.TestSubagentStop_DecisionCorrelation},

	{"TestSubagentStop_ParallelAgentCompletion", _test.TestSubagentStop_ParallelAgentCompletion},

	{"TestSubagentStop_TierSpecificPrompts", _test.TestSubagentStop_TierSpecificPrompts},

	{"TestTaskValidation_CompleteWorkflow", _test.TestTaskValidation_CompleteWorkflow},

	{"TestTaskValidation_RealWorldScenarios", _test.TestTaskValidation_RealWorldScenarios},

}

var benchmarks = []testing.InternalBenchmark{

	{"BenchmarkHookResponsePipeline", _test.BenchmarkHookResponsePipeline},

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/Bucket-Chemist/GOgent-Fortress/test/integration"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	_test.TestMain(m)
	os.Exit(int(reflect.ValueOf(m).Elem().FieldByName("exitCode").Int()))

}

