
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/Bucket-Chemist/GOgent-Fortress/internal/cli"


	_xtest "github.com/Bucket-Chemist/GOgent-Fortress/internal/cli_test"

)

var tests = []testing.InternalTest{

	{"TestNDJSONReader_ValidJSON", _test.TestNDJSONReader_ValidJSON},

	{"TestNDJSONReader_MalformedJSON", _test.TestNDJSONReader_MalformedJSON},

	{"TestNDJSONReader_LongLines", _test.TestNDJSONReader_LongLines},

	{"TestNDJSONReader_EOF", _test.TestNDJSONReader_EOF},

	{"TestNDJSONWriter_ValidJSON", _test.TestNDJSONWriter_ValidJSON},

	{"TestNDJSONWriter_MultipleWrites", _test.TestNDJSONWriter_MultipleWrites},

	{"TestNDJSONWriter_InvalidJSON", _test.TestNDJSONWriter_InvalidJSON},

	{"TestNDJSONWriter_ThreadSafety", _test.TestNDJSONWriter_ThreadSafety},

	{"TestConfig_Defaults", _test.TestConfig_Defaults},

	{"TestConfig_CustomValues", _test.TestConfig_CustomValues},

	{"TestNewClaudeProcess_Defaults", _test.TestNewClaudeProcess_Defaults},

	{"TestNewClaudeProcess_CustomConfig", _test.TestNewClaudeProcess_CustomConfig},

	{"TestClaudeProcess_StartStop", _test.TestClaudeProcess_StartStop},

	{"TestClaudeProcess_DoubleStart", _test.TestClaudeProcess_DoubleStart},

	{"TestClaudeProcess_StopIdempotent", _test.TestClaudeProcess_StopIdempotent},

	{"TestClaudeProcess_SendBeforeStart", _test.TestClaudeProcess_SendBeforeStart},

	{"TestClaudeProcess_SendJSON", _test.TestClaudeProcess_SendJSON},

	{"TestClaudeProcess_EventReading", _test.TestClaudeProcess_EventReading},

	{"TestClaudeProcess_EchoMessage", _test.TestClaudeProcess_EchoMessage},

	{"TestClaudeProcess_GracefulShutdown", _test.TestClaudeProcess_GracefulShutdown},

	{"TestClaudeProcess_ChannelsClosed", _test.TestClaudeProcess_ChannelsClosed},

	{"TestParseEvent_ValidJSON", _test.TestParseEvent_ValidJSON},

	{"TestParseEvent_InvalidJSON", _test.TestParseEvent_InvalidJSON},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

	{"ExampleClaudeProcess", _xtest.ExampleClaudeProcess, "Received event type: system\nReceived event type: assistant\n", false},

	{"ExampleClaudeProcess_structured", _xtest.ExampleClaudeProcess_structured, "Session ID: example-session\nRunning: true\n", false},

	{"ExampleNDJSONWriter", _xtest.ExampleNDJSONWriter, "NDJSON Writer example - see streams_test.go for full usage\n", false},

}

func init() {

	testdeps.ImportPath = "github.com/Bucket-Chemist/GOgent-Fortress/internal/cli"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

