#!/bin/bash
# Helper commands for manual monitoring

echo "=== Monitoring Commands ==="
echo ""
echo "1. Count active Claude processes:"
echo "   ps aux | grep 'claude -p' | grep -v grep | wc -l"
echo ""
echo "2. Show all Claude processes with nesting levels:"
echo "   ps e -o pid,cmd | grep claude | grep GOGENT_NESTING_LEVEL"
echo ""
echo "3. Watch TUI output in real-time:"
echo "   tail -f $TUI_OUTPUT"
echo ""
echo "4. Check spawn registry (if exists):"
echo "   cat /tmp/gogent-spawn-registry.json 2>/dev/null | jq"
echo ""
echo "5. Kill all Claude processes (emergency):"
echo "   pkill -f 'claude -p'"
echo ""
