
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/Bucket-Chemist/GOgent-Fortress/pkg/telemetry"


)

var tests = []testing.InternalTest{

	{"TestNewAgentLifecycleEvent", _test.TestNewAgentLifecycleEvent},

	{"TestNewAgentLifecycleEvent_CompleteEvent", _test.TestNewAgentLifecycleEvent_CompleteEvent},

	{"TestNewAgentLifecycleEvent_ErrorEvent", _test.TestNewAgentLifecycleEvent_ErrorEvent},

	{"TestLogAgentLifecycle", _test.TestLogAgentLifecycle},

	{"TestReadAgentLifecycleLogs_Empty", _test.TestReadAgentLifecycleLogs_Empty},

	{"TestReadAgentLifecycleLogs", _test.TestReadAgentLifecycleLogs},

	{"TestReadAgentLifecycleLogs_FilterBySession", _test.TestReadAgentLifecycleLogs_FilterBySession},

	{"TestReadAgentLifecycleLogs_MalformedLines", _test.TestReadAgentLifecycleLogs_MalformedLines},

	{"TestReadAgentLifecycleLogs_EmptyLines", _test.TestReadAgentLifecycleLogs_EmptyLines},

	{"TestAgentLifecycle_ThreadSafety", _test.TestAgentLifecycle_ThreadSafety},

	{"TestAgentLifecycle_AllFieldsSerialized", _test.TestAgentLifecycle_AllFieldsSerialized},

	{"TestAgentLifecycle_TaskDescriptionTruncation", _test.TestAgentLifecycle_TaskDescriptionTruncation},

	{"TestXDGComplianceAgentLifecycle", _test.TestXDGComplianceAgentLifecycle},

	{"TestAgentLifecycle_SpawnAndCompleteFlow", _test.TestAgentLifecycle_SpawnAndCompleteFlow},

	{"TestAgentLifecycle_MultipleAgentsParallel", _test.TestAgentLifecycle_MultipleAgentsParallel},

	{"TestNewAgentCollaboration", _test.TestNewAgentCollaboration},

	{"TestLogCollaboration_GlobalPath", _test.TestLogCollaboration_GlobalPath},

	{"TestReadCollaborationLogs_Empty", _test.TestReadCollaborationLogs_Empty},

	{"TestReadCollaborationLogs", _test.TestReadCollaborationLogs},

	{"TestCalculateCollaborationStats", _test.TestCalculateCollaborationStats},

	{"TestXDGComplianceCollaboration", _test.TestXDGComplianceCollaboration},

	{"TestCollaborationWithSwarmFields", _test.TestCollaborationWithSwarmFields},

	{"TestChainDepthTracking", _test.TestChainDepthTracking},

	{"TestCalculateCollaborationStats_EmptyLogs", _test.TestCalculateCollaborationStats_EmptyLogs},

	{"TestReadCollaborationLogs_MalformedLines", _test.TestReadCollaborationLogs_MalformedLines},

	{"TestReadCollaborationLogs_EmptyLines", _test.TestReadCollaborationLogs_EmptyLines},

	{"TestCollaboration_ThreadSafety", _test.TestCollaboration_ThreadSafety},

	{"TestCollaboration_AllFieldsSerialized", _test.TestCollaboration_AllFieldsSerialized},

	{"TestLogCollaboration_PermissionError", _test.TestLogCollaboration_PermissionError},

	{"TestCalculateInvocationCost_Sonnet", _test.TestCalculateInvocationCost_Sonnet},

	{"TestCalculateInvocationCost_WithThinking", _test.TestCalculateInvocationCost_WithThinking},

	{"TestCalculateInvocationCost_Opus", _test.TestCalculateInvocationCost_Opus},

	{"TestCalculateInvocationCost_Haiku", _test.TestCalculateInvocationCost_Haiku},

	{"TestCalculateInvocationCost_HaikuThinking", _test.TestCalculateInvocationCost_HaikuThinking},

	{"TestCalculateInvocationCost_External", _test.TestCalculateInvocationCost_External},

	{"TestCalculateInvocationCost_UnknownTier", _test.TestCalculateInvocationCost_UnknownTier},

	{"TestCalculateAgentCosts_MultipleAgents", _test.TestCalculateAgentCosts_MultipleAgents},

	{"TestCalculateAgentCosts_EmptyAgent", _test.TestCalculateAgentCosts_EmptyAgent},

	{"TestCalculateTierCosts_Distribution", _test.TestCalculateTierCosts_Distribution},

	{"TestCalculateTierCosts_EmptyTier", _test.TestCalculateTierCosts_EmptyTier},

	{"TestCalculateSessionCost_Total", _test.TestCalculateSessionCost_Total},

	{"TestCalculateSessionCost_Empty", _test.TestCalculateSessionCost_Empty},

	{"TestCalculateSessionCostSummary_Complete", _test.TestCalculateSessionCostSummary_Complete},

	{"TestLoadTierPricing_FallbackToDefault", _test.TestLoadTierPricing_FallbackToDefault},

	{"TestGetTierCostRate_AllTiers", _test.TestGetTierCostRate_AllTiers},

	{"TestFormatCost_SmallAmounts", _test.TestFormatCost_SmallAmounts},

	{"TestFormatCost_LargeAmounts", _test.TestFormatCost_LargeAmounts},

	{"TestFormatCost_Boundary", _test.TestFormatCost_Boundary},

	{"TestFormatCost_Zero", _test.TestFormatCost_Zero},

	{"TestCalculateAgentCosts_TotalTokens", _test.TestCalculateAgentCosts_TotalTokens},

	{"TestCalculateTierCosts_TotalTokens", _test.TestCalculateTierCosts_TotalTokens},

	{"TestLogEscalation_Basic", _test.TestLogEscalation_Basic},

	{"TestLogEscalation_InvalidTriggerType", _test.TestLogEscalation_InvalidTriggerType},

	{"TestLogEscalation_ValidTriggerTypes", _test.TestLogEscalation_ValidTriggerTypes},

	{"TestLogEscalation_EmptyTriggerType", _test.TestLogEscalation_EmptyTriggerType},

	{"TestLogEscalation_TimestampAutoPopulated", _test.TestLogEscalation_TimestampAutoPopulated},

	{"TestLogEscalation_DualWrite", _test.TestLogEscalation_DualWrite},

	{"TestLogEscalation_ProjectWriteFailure_GracefulDegradation", _test.TestLogEscalation_ProjectWriteFailure_GracefulDegradation},

	{"TestLogEscalation_WithGAPDoc", _test.TestLogEscalation_WithGAPDoc},

	{"TestLogEscalation_WithCustomOutcome", _test.TestLogEscalation_WithCustomOutcome},

	{"TestLoadEscalations_ValidFile", _test.TestLoadEscalations_ValidFile},

	{"TestLoadEscalations_MissingFile", _test.TestLoadEscalations_MissingFile},

	{"TestLoadEscalations_MalformedLines", _test.TestLoadEscalations_MalformedLines},

	{"TestLoadEscalations_EmptyLines", _test.TestLoadEscalations_EmptyLines},

	{"TestLoadEscalations_EmptyFile", _test.TestLoadEscalations_EmptyFile},

	{"TestUpdateEscalationOutcome_Success", _test.TestUpdateEscalationOutcome_Success},

	{"TestUpdateEscalationOutcome_NotFound", _test.TestUpdateEscalationOutcome_NotFound},

	{"TestUpdateEscalationOutcome_InvalidOutcome", _test.TestUpdateEscalationOutcome_InvalidOutcome},

	{"TestUpdateEscalationOutcome_ValidOutcomes", _test.TestUpdateEscalationOutcome_ValidOutcomes},

	{"TestUpdateEscalationOutcome_PreservesOtherEscalations", _test.TestUpdateEscalationOutcome_PreservesOtherEscalations},

	{"TestFilterEscalations_ByOutcome", _test.TestFilterEscalations_ByOutcome},

	{"TestFilterEscalations_ByTriggerType", _test.TestFilterEscalations_ByTriggerType},

	{"TestFilterEscalations_ByToTier", _test.TestFilterEscalations_ByToTier},

	{"TestFilterEscalations_ByFromAgent", _test.TestFilterEscalations_ByFromAgent},

	{"TestFilterEscalations_BySince", _test.TestFilterEscalations_BySince},

	{"TestFilterEscalations_WithLimit", _test.TestFilterEscalations_WithLimit},

	{"TestFilterEscalations_MultipleFilters", _test.TestFilterEscalations_MultipleFilters},

	{"TestFilterEscalations_NoMatches", _test.TestFilterEscalations_NoMatches},

	{"TestFilterEscalations_EmptyInput", _test.TestFilterEscalations_EmptyInput},

	{"TestFilterEscalations_NoFiltersApplied", _test.TestFilterEscalations_NoFiltersApplied},

	{"TestGetEscalationsLogPath_XDGCompliance", _test.TestGetEscalationsLogPath_XDGCompliance},

	{"TestGetProjectEscalationsLogPath", _test.TestGetProjectEscalationsLogPath},

	{"TestLogEscalation_DirectoryAutoCreated", _test.TestLogEscalation_DirectoryAutoCreated},

	{"TestLogEscalation_MultipleEscalations", _test.TestLogEscalation_MultipleEscalations},

	{"TestLogEscalation_AllFields", _test.TestLogEscalation_AllFields},

	{"TestClusterEscalationsByFromAgent", _test.TestClusterEscalationsByFromAgent},

	{"TestClusterEscalationsByTrigger", _test.TestClusterEscalationsByTrigger},

	{"TestCalculateEscalationROI", _test.TestCalculateEscalationROI},

	{"TestAnalyzeEscalationLatency", _test.TestAnalyzeEscalationLatency},

	{"TestGetEscalationTrend", _test.TestGetEscalationTrend},

	{"TestLogInvocation_GlobalWrite", _test.TestLogInvocation_GlobalWrite},

	{"TestLogInvocation_DualWrite", _test.TestLogInvocation_DualWrite},

	{"TestLogInvocation_TimestampAutoPopulated", _test.TestLogInvocation_TimestampAutoPopulated},

	{"TestLogInvocation_FailureInvocation", _test.TestLogInvocation_FailureInvocation},

	{"TestLogInvocation_ThinkingTokens", _test.TestLogInvocation_ThinkingTokens},

	{"TestLogInvocation_ParentTaskID", _test.TestLogInvocation_ParentTaskID},

	{"TestLogInvocation_ProjectWriteFailure_GracefulDegradation", _test.TestLogInvocation_ProjectWriteFailure_GracefulDegradation},

	{"TestLoadInvocations_ValidFile", _test.TestLoadInvocations_ValidFile},

	{"TestLoadInvocations_MissingFile", _test.TestLoadInvocations_MissingFile},

	{"TestLoadInvocations_MalformedLines", _test.TestLoadInvocations_MalformedLines},

	{"TestLoadInvocations_EmptyLines", _test.TestLoadInvocations_EmptyLines},

	{"TestLoadInvocations_EmptyFile", _test.TestLoadInvocations_EmptyFile},

	{"TestGetInvocationsLogPath_XDGCompliance", _test.TestGetInvocationsLogPath_XDGCompliance},

	{"TestGetInvocationsLogPath_XDGCacheHome", _test.TestGetInvocationsLogPath_XDGCacheHome},

	{"TestGetProjectInvocationsLogPath", _test.TestGetProjectInvocationsLogPath},

	{"TestLogInvocation_DirectoryAutoCreated", _test.TestLogInvocation_DirectoryAutoCreated},

	{"TestLogInvocation_MultipleInvocations", _test.TestLogInvocation_MultipleInvocations},

	{"TestLogInvocation_EmptyToolsUsed", _test.TestLogInvocation_EmptyToolsUsed},

	{"TestLogInvocation_NilToolsUsed", _test.TestLogInvocation_NilToolsUsed},

	{"TestAgentInvocation_JSONRoundtrip", _test.TestAgentInvocation_JSONRoundtrip},

	{"TestAgentInvocation_OmitEmptyFields", _test.TestAgentInvocation_OmitEmptyFields},

	{"TestLogInvocation_GlobalWriteFailure", _test.TestLogInvocation_GlobalWriteFailure},

	{"TestClusterInvocationsByAgent_SingleAgent", _test.TestClusterInvocationsByAgent_SingleAgent},

	{"TestClusterInvocationsByAgent_MultipleAgents", _test.TestClusterInvocationsByAgent_MultipleAgents},

	{"TestClusterInvocationsByAgent_EmptyAgent", _test.TestClusterInvocationsByAgent_EmptyAgent},

	{"TestClusterInvocationsByAgent_EmptyInput", _test.TestClusterInvocationsByAgent_EmptyInput},

	{"TestClusterInvocationsByAgent_Samples", _test.TestClusterInvocationsByAgent_Samples},

	{"TestClusterInvocationsByAgent_AllSuccess", _test.TestClusterInvocationsByAgent_AllSuccess},

	{"TestClusterInvocationsByAgent_AllFailure", _test.TestClusterInvocationsByAgent_AllFailure},

	{"TestClusterInvocationsByTier_SingleTier", _test.TestClusterInvocationsByTier_SingleTier},

	{"TestClusterInvocationsByTier_MultipleTiers", _test.TestClusterInvocationsByTier_MultipleTiers},

	{"TestClusterInvocationsByTier_EmptyTier", _test.TestClusterInvocationsByTier_EmptyTier},

	{"TestClusterInvocationsByTier_EmptyInput", _test.TestClusterInvocationsByTier_EmptyInput},

	{"TestClusterInvocationsByTier_EmptyAgentInBreakdown", _test.TestClusterInvocationsByTier_EmptyAgentInBreakdown},

	{"TestGetTopAgentsByUsage_Basic", _test.TestGetTopAgentsByUsage_Basic},

	{"TestGetTopAgentsByUsage_WithLimit", _test.TestGetTopAgentsByUsage_WithLimit},

	{"TestGetTopAgentsByUsage_EmptyInput", _test.TestGetTopAgentsByUsage_EmptyInput},

	{"TestGetTopAgentsByErrorRate_Basic", _test.TestGetTopAgentsByErrorRate_Basic},

	{"TestGetTopAgentsByErrorRate_MinInvocations", _test.TestGetTopAgentsByErrorRate_MinInvocations},

	{"TestGetTopAgentsByErrorRate_WithLimit", _test.TestGetTopAgentsByErrorRate_WithLimit},

	{"TestGetTopAgentsByErrorRate_AllFiltered", _test.TestGetTopAgentsByErrorRate_AllFiltered},

	{"TestGetTopAgentsByLatency_Basic", _test.TestGetTopAgentsByLatency_Basic},

	{"TestGetTopAgentsByLatency_WithLimit", _test.TestGetTopAgentsByLatency_WithLimit},

	{"TestGetTopAgentsByLatency_EmptyInput", _test.TestGetTopAgentsByLatency_EmptyInput},

	{"TestToolEventWorkflow_LogAndAnalyze", _test.TestToolEventWorkflow_LogAndAnalyze},

	{"TestToolEventWorkflow_CostTracking", _test.TestToolEventWorkflow_CostTracking},

	{"TestSequenceTracking_Integration", _test.TestSequenceTracking_Integration},

	{"TestTaskClassification_Integration", _test.TestTaskClassification_Integration},

	{"TestDualWrite_Integration", _test.TestDualWrite_Integration},

	{"TestUnderstandingContext_Integration", _test.TestUnderstandingContext_Integration},

	{"TestTaskTypeAndDomainLabels", _test.TestTaskTypeAndDomainLabels},

	{"TestTaskDomainDetection", _test.TestTaskDomainDetection},

	{"TestErrorHandling_Integration", _test.TestErrorHandling_Integration},

	{"TestMalformedJSON_Integration", _test.TestMalformedJSON_Integration},

	{"TestEmptySessionStats", _test.TestEmptySessionStats},

	{"TestJSONLFormatCompliance", _test.TestJSONLFormatCompliance},

	{"TestProjectPathWrite", _test.TestProjectPathWrite},

	{"TestReadMLToolEvents_EmptyLines", _test.TestReadMLToolEvents_EmptyLines},

	{"TestLogMLToolEvent_GlobalPath", _test.TestLogMLToolEvent_GlobalPath},

	{"TestLogMLToolEvent_ProjectPath", _test.TestLogMLToolEvent_ProjectPath},

	{"TestLogMLToolEvent_NoProjectPath", _test.TestLogMLToolEvent_NoProjectPath},

	{"TestReadMLToolEvents_Empty", _test.TestReadMLToolEvents_Empty},

	{"TestReadMLToolEvents", _test.TestReadMLToolEvents},

	{"TestReadMLToolEvents_MalformedLines", _test.TestReadMLToolEvents_MalformedLines},

	{"TestCalculateMLSessionStats", _test.TestCalculateMLSessionStats},

	{"TestCalculateMLSessionStats_Empty", _test.TestCalculateMLSessionStats_Empty},

	{"TestDualWrite", _test.TestDualWrite},

	{"TestDirExists", _test.TestDirExists},

	{"TestAppendMLToolEvent", _test.TestAppendMLToolEvent},

	{"TestXDGCompliance", _test.TestXDGCompliance},

	{"TestTotalTokens", _test.TestTotalTokens},

	{"TestEstimatedCost", _test.TestEstimatedCost},

	{"TestEstimatedCost_Unknown", _test.TestEstimatedCost_Unknown},

	{"TestEnrichWithSequence", _test.TestEnrichWithSequence},

	{"TestEnrichWithClassification", _test.TestEnrichWithClassification},

	{"TestPostToolEventWithSequenceTracking", _test.TestPostToolEventWithSequenceTracking},

	{"TestNewRoutingDecision", _test.TestNewRoutingDecision},

	{"TestNewRoutingDecision_TruncatesLongDescription", _test.TestNewRoutingDecision_TruncatesLongDescription},

	{"TestLogRoutingDecision", _test.TestLogRoutingDecision},

	{"TestLogRoutingDecision_MultipleDecisions", _test.TestLogRoutingDecision_MultipleDecisions},

	{"TestUpdateDecisionOutcome", _test.TestUpdateDecisionOutcome},

	{"TestUpdateDecisionOutcome_MultipleUpdates", _test.TestUpdateDecisionOutcome_MultipleUpdates},

	{"TestUnderstandingQualityFields", _test.TestUnderstandingQualityFields},

	{"TestTruncateDescription", _test.TestTruncateDescription},

	{"TestNewRoutingDecision_IntegratesClassifyTask", _test.TestNewRoutingDecision_IntegratesClassifyTask},

	{"TestLogRoutingDecision_ErrorMessages", _test.TestLogRoutingDecision_ErrorMessages},

	{"TestDecisionFileSeparation", _test.TestDecisionFileSeparation},

	{"TestXDGDataHomeFallback", _test.TestXDGDataHomeFallback},

	{"TestAppendDecisionUpdate_CreatesDirectoryIfNeeded", _test.TestAppendDecisionUpdate_CreatesDirectoryIfNeeded},

	{"TestCompleteRoutingDecisionWorkflow", _test.TestCompleteRoutingDecisionWorkflow},

	{"TestLogScoutRecommendation_Basic", _test.TestLogScoutRecommendation_Basic},

	{"TestLogScoutRecommendation_NotFollowed", _test.TestLogScoutRecommendation_NotFollowed},

	{"TestLogScoutRecommendation_InvalidConfidence", _test.TestLogScoutRecommendation_InvalidConfidence},

	{"TestLogScoutRecommendation_ValidConfidenceBoundaries", _test.TestLogScoutRecommendation_ValidConfidenceBoundaries},

	{"TestLogScoutRecommendation_InvalidScoutType", _test.TestLogScoutRecommendation_InvalidScoutType},

	{"TestLogScoutRecommendation_ValidScoutTypes", _test.TestLogScoutRecommendation_ValidScoutTypes},

	{"TestLogScoutRecommendation_EmptyScoutType", _test.TestLogScoutRecommendation_EmptyScoutType},

	{"TestLogScoutRecommendation_ProjectDir", _test.TestLogScoutRecommendation_ProjectDir},

	{"TestLoadScoutRecommendations_ValidFile", _test.TestLoadScoutRecommendations_ValidFile},

	{"TestLoadScoutRecommendations_MissingFile", _test.TestLoadScoutRecommendations_MissingFile},

	{"TestLoadScoutRecommendations_EmptyFile", _test.TestLoadScoutRecommendations_EmptyFile},

	{"TestLoadScoutRecommendations_MalformedLines", _test.TestLoadScoutRecommendations_MalformedLines},

	{"TestLoadScoutRecommendations_BlankLines", _test.TestLoadScoutRecommendations_BlankLines},

	{"TestUpdateScoutOutcome_Success", _test.TestUpdateScoutOutcome_Success},

	{"TestUpdateScoutOutcome_NotFound", _test.TestUpdateScoutOutcome_NotFound},

	{"TestUpdateScoutOutcome_InvalidOutcome", _test.TestUpdateScoutOutcome_InvalidOutcome},

	{"TestUpdateScoutOutcome_ValidOutcomes", _test.TestUpdateScoutOutcome_ValidOutcomes},

	{"TestUpdateScoutOutcome_MultipleRecommendations", _test.TestUpdateScoutOutcome_MultipleRecommendations},

	{"TestFilterScoutRecommendations_ByFollowed", _test.TestFilterScoutRecommendations_ByFollowed},

	{"TestFilterScoutRecommendations_ByMinConfidence", _test.TestFilterScoutRecommendations_ByMinConfidence},

	{"TestFilterScoutRecommendations_ByScoutType", _test.TestFilterScoutRecommendations_ByScoutType},

	{"TestFilterScoutRecommendations_ByRecommendedTier", _test.TestFilterScoutRecommendations_ByRecommendedTier},

	{"TestFilterScoutRecommendations_ByTaskOutcome", _test.TestFilterScoutRecommendations_ByTaskOutcome},

	{"TestFilterScoutRecommendations_BySince", _test.TestFilterScoutRecommendations_BySince},

	{"TestFilterScoutRecommendations_WithLimit", _test.TestFilterScoutRecommendations_WithLimit},

	{"TestFilterScoutRecommendations_MultipleFilters", _test.TestFilterScoutRecommendations_MultipleFilters},

	{"TestFilterScoutRecommendations_NoFilters", _test.TestFilterScoutRecommendations_NoFilters},

	{"TestFilterScoutRecommendations_EmptyInput", _test.TestFilterScoutRecommendations_EmptyInput},

	{"TestGetScoutLogPath", _test.TestGetScoutLogPath},

	{"TestGetProjectScoutLogPath", _test.TestGetProjectScoutLogPath},

	{"TestScoutRecommendation_FollowedAutoDetection", _test.TestScoutRecommendation_FollowedAutoDetection},

	{"TestCalculateScoutAccuracy_Basic", _test.TestCalculateScoutAccuracy_Basic},

	{"TestCalculateScoutAccuracy_NoOutcomes", _test.TestCalculateScoutAccuracy_NoOutcomes},

	{"TestCalculateScoutAccuracy_EmptyInput", _test.TestCalculateScoutAccuracy_EmptyInput},

	{"TestCalculateScoutAccuracy_ByScoutType", _test.TestCalculateScoutAccuracy_ByScoutType},

	{"TestCalculateScoutAccuracy_UnknownScoutType", _test.TestCalculateScoutAccuracy_UnknownScoutType},

	{"TestCalculateScoutAccuracy_IgnoredAccuracy", _test.TestCalculateScoutAccuracy_IgnoredAccuracy},

	{"TestCalculateScoutAccuracy_ComplianceRate", _test.TestCalculateScoutAccuracy_ComplianceRate},

	{"TestCalculateScoutAccuracy_DivisionByZero", _test.TestCalculateScoutAccuracy_DivisionByZero},

	{"TestAnalyzeConfidenceCorrelation_Basic", _test.TestAnalyzeConfidenceCorrelation_Basic},

	{"TestAnalyzeConfidenceCorrelation_ConfidenceExactlyOne", _test.TestAnalyzeConfidenceCorrelation_ConfidenceExactlyOne},

	{"TestAnalyzeConfidenceCorrelation_EmptyInput", _test.TestAnalyzeConfidenceCorrelation_EmptyInput},

	{"TestAnalyzeConfidenceCorrelation_NoOutcomes", _test.TestAnalyzeConfidenceCorrelation_NoOutcomes},

	{"TestAnalyzeConfidenceCorrelation_FollowedRate", _test.TestAnalyzeConfidenceCorrelation_FollowedRate},

	{"TestGetComplianceImpact_FollowBetter", _test.TestGetComplianceImpact_FollowBetter},

	{"TestGetComplianceImpact_IgnoreBetter", _test.TestGetComplianceImpact_IgnoreBetter},

	{"TestGetComplianceImpact_Neutral", _test.TestGetComplianceImpact_Neutral},

	{"TestGetComplianceImpact_InsufficientData", _test.TestGetComplianceImpact_InsufficientData},

	{"TestGetComplianceImpact_LowSignificance", _test.TestGetComplianceImpact_LowSignificance},

	{"TestGetComplianceImpact_MediumSignificance", _test.TestGetComplianceImpact_MediumSignificance},

	{"TestGetComplianceImpact_HighSignificance", _test.TestGetComplianceImpact_HighSignificance},

	{"TestGetComplianceImpact_EmptyInput", _test.TestGetComplianceImpact_EmptyInput},

	{"TestClusterRecommendationsByTier_Basic", _test.TestClusterRecommendationsByTier_Basic},

	{"TestClusterRecommendationsByTier_EmptyTier", _test.TestClusterRecommendationsByTier_EmptyTier},

	{"TestClusterRecommendationsByTier_AvgConfidence", _test.TestClusterRecommendationsByTier_AvgConfidence},

	{"TestClusterRecommendationsByTier_EmptyInput", _test.TestClusterRecommendationsByTier_EmptyInput},

	{"TestClusterRecommendationsByTier_ZeroComplianceRate", _test.TestClusterRecommendationsByTier_ZeroComplianceRate},

	{"TestGetScoutPerformanceSummary_HighAccuracy", _test.TestGetScoutPerformanceSummary_HighAccuracy},

	{"TestGetScoutPerformanceSummary_LowAccuracy", _test.TestGetScoutPerformanceSummary_LowAccuracy},

	{"TestGetScoutPerformanceSummary_InsufficientData", _test.TestGetScoutPerformanceSummary_InsufficientData},

	{"TestGetScoutPerformanceSummary_ModeratePerformance", _test.TestGetScoutPerformanceSummary_ModeratePerformance},

	{"TestGetScoutPerformanceSummary_AllComponentsPresent", _test.TestGetScoutPerformanceSummary_AllComponentsPresent},

	{"TestClassifyTask_Implementation", _test.TestClassifyTask_Implementation},

	{"TestClassifyTask_Search", _test.TestClassifyTask_Search},

	{"TestClassifyTask_Domain", _test.TestClassifyTask_Domain},

	{"TestClassifyTask_Understanding", _test.TestClassifyTask_Understanding},

	{"TestClassifyTask_Accuracy", _test.TestClassifyTask_Accuracy},

	{"TestTaskTypeLabels", _test.TestTaskTypeLabels},

	{"TestTaskDomainLabels", _test.TestTaskDomainLabels},

	{"TestClassifyTask_UnknownTypeAndDomain", _test.TestClassifyTask_UnknownTypeAndDomain},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/Bucket-Chemist/GOgent-Fortress/pkg/telemetry"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

