
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/Bucket-Chemist/GOgent-Fortress/cmd/gogent-archive"


)

var tests = []testing.InternalTest{

	{"TestRun_ValidSessionEnd", _test.TestRun_ValidSessionEnd},

	{"TestRun_InvalidJSON", _test.TestRun_InvalidJSON},

	{"TestRun_MissingProjectDir", _test.TestRun_MissingProjectDir},

	{"TestRun_STDINTimeout", _test.TestRun_STDINTimeout},

	{"TestMain_ErrorPath", _test.TestMain_ErrorPath},

	{"TestOutputError", _test.TestOutputError},

	{"TestRun_WithMultipleMetrics", _test.TestRun_WithMultipleMetrics},

	{"TestBuildSessionActions", _test.TestBuildSessionActions},

	{"TestBuildSessionActions_NoHandoff", _test.TestBuildSessionActions_NoHandoff},

	{"TestBuildSessionActions_SessionNotFound", _test.TestBuildSessionActions_SessionNotFound},

	{"TestUpdateIntentsWithOutcomes", _test.TestUpdateIntentsWithOutcomes},

	{"TestUpdateIntentsWithOutcomes_MissingFile", _test.TestUpdateIntentsWithOutcomes_MissingFile},

	{"TestGenerateWeeklySummary_DefaultRange", _test.TestGenerateWeeklySummary_DefaultRange},

	{"TestGenerateWeeklySummary_CustomDateRange", _test.TestGenerateWeeklySummary_CustomDateRange},

	{"TestGenerateWeeklySummary_IntentsOnlyFlag", _test.TestGenerateWeeklySummary_IntentsOnlyFlag},

	{"TestGenerateWeeklySummary_NoIntents", _test.TestGenerateWeeklySummary_NoIntents},

	{"TestGenerateWeeklySummary_DriftDetection", _test.TestGenerateWeeklySummary_DriftDetection},

	{"TestParseSinceFilter_DurationFormat", _test.TestParseSinceFilter_DurationFormat},

	{"TestParseSinceFilter_DateFormat", _test.TestParseSinceFilter_DateFormat},

	{"TestParseSinceFilter_EdgeCase_0Days", _test.TestParseSinceFilter_EdgeCase_0Days},

	{"TestParseSinceFilter_EdgeCase_LeapYear", _test.TestParseSinceFilter_EdgeCase_LeapYear},

	{"TestFilterBetween_ValidRange", _test.TestFilterBetween_ValidRange},

	{"TestFilterBetween_InclusiveBoundaries", _test.TestFilterBetween_InclusiveBoundaries},

	{"TestShowSession_ValidSession", _test.TestShowSession_ValidSession},

	{"TestShowSession_RendersFullMarkdown", _test.TestShowSession_RendersFullMarkdown},

	{"TestFilterSince_EmptyHandoffs", _test.TestFilterSince_EmptyHandoffs},

	{"TestFilterBetween_EmptyHandoffs", _test.TestFilterBetween_EmptyHandoffs},

	{"TestListSharpEdges_Empty", _test.TestListSharpEdges_Empty},

	{"TestListSharpEdges_WithSeverityFilter", _test.TestListSharpEdges_WithSeverityFilter},

	{"TestListSharpEdges_WithUnresolvedFilter", _test.TestListSharpEdges_WithUnresolvedFilter},

	{"TestListSharpEdges_WithFileFilter", _test.TestListSharpEdges_WithFileFilter},

	{"TestListSharpEdges_WithErrorTypeFilter", _test.TestListSharpEdges_WithErrorTypeFilter},

	{"TestListSharpEdges_WithSinceFilter", _test.TestListSharpEdges_WithSinceFilter},

	{"TestListSharpEdges_TableFormat", _test.TestListSharpEdges_TableFormat},

	{"TestListUserIntents_Empty", _test.TestListUserIntents_Empty},

	{"TestListUserIntents_WithSourceFilter", _test.TestListUserIntents_WithSourceFilter},

	{"TestListUserIntents_HasActionFilter", _test.TestListUserIntents_HasActionFilter},

	{"TestListUserIntents_WithConfidenceFilter", _test.TestListUserIntents_WithConfidenceFilter},

	{"TestListUserIntents_WithSinceFilter", _test.TestListUserIntents_WithSinceFilter},

	{"TestListUserIntents_TableFormat", _test.TestListUserIntents_TableFormat},

	{"TestTruncateForTable", _test.TestTruncateForTable},

	{"TestParseSinceFilter_Duration", _test.TestParseSinceFilter_Duration},

	{"TestParseSinceFilter_Date", _test.TestParseSinceFilter_Date},

	{"TestPrintHelp_IncludesSharpEdgesCommands", _test.TestPrintHelp_IncludesSharpEdgesCommands},

	{"TestPrintHelp_IncludesUserIntentsCommands", _test.TestPrintHelp_IncludesUserIntentsCommands},

	{"TestListSharpEdges_MissingFile", _test.TestListSharpEdges_MissingFile},

	{"TestListUserIntents_MissingFile", _test.TestListUserIntents_MissingFile},

	{"TestListSharpEdges_DefaultSeverityDash", _test.TestListSharpEdges_DefaultSeverityDash},

	{"TestListSessions_EmptyFile", _test.TestListSessions_EmptyFile},

	{"TestListSessions_MultipleHandoffs", _test.TestListSessions_MultipleHandoffs},

	{"TestShowSession_Found", _test.TestShowSession_Found},

	{"TestStats_EmptyFile", _test.TestStats_EmptyFile},

	{"TestStats_MultipleHandoffs", _test.TestStats_MultipleHandoffs},

	{"TestFilterSince_Duration", _test.TestFilterSince_Duration},

	{"TestFilterBetween_DateRange", _test.TestFilterBetween_DateRange},

	{"TestFilterByArtifacts_Clean", _test.TestFilterByArtifacts_Clean},

	{"TestFilterByArtifacts_HasSharpEdges", _test.TestFilterByArtifacts_HasSharpEdges},

	{"TestFilterByArtifacts_HasViolations", _test.TestFilterByArtifacts_HasViolations},

	{"TestFilterByArtifacts_CombinedFilters", _test.TestFilterByArtifacts_CombinedFilters},

	{"TestFilterSince_DateFormat", _test.TestFilterSince_DateFormat},

	{"TestFilterSince_EmptyResult", _test.TestFilterSince_EmptyResult},

	{"TestFilterBetween_EmptyResult", _test.TestFilterBetween_EmptyResult},

	{"TestFilterBetween_SingleDay", _test.TestFilterBetween_SingleDay},

	{"TestGetVersion", _test.TestGetVersion},

	{"TestPrintHelp", _test.TestPrintHelp},

	{"TestGetProjectDir_FromEnv", _test.TestGetProjectDir_FromEnv},

	{"TestGetProjectDir_Fallback", _test.TestGetProjectDir_Fallback},

	{"TestListSessions_WithSinceFlag", _test.TestListSessions_WithSinceFlag},

	{"TestListSessions_WithCleanFlag", _test.TestListSessions_WithCleanFlag},

	{"TestListSessions_NoMatchesAfterFilter", _test.TestListSessions_NoMatchesAfterFilter},

	{"TestStats_NoBreakdownsForCleanSessions", _test.TestStats_NoBreakdownsForCleanSessions},

	{"TestListSessions_WithBetweenFlag", _test.TestListSessions_WithBetweenFlag},

	{"TestListSessions_WithHasSharpEdgesFlag", _test.TestListSessions_WithHasSharpEdgesFlag},

	{"TestListSessions_WithHasViolationsFlag", _test.TestListSessions_WithHasViolationsFlag},

	{"TestFilterSince_ZeroDays", _test.TestFilterSince_ZeroDays},

	{"TestFilterSince_LongDuration", _test.TestFilterSince_LongDuration},

	{"TestFilterBetween_FullYearRange", _test.TestFilterBetween_FullYearRange},

	{"TestFilterByArtifacts_AllFiltersOff", _test.TestFilterByArtifacts_AllFiltersOff},

	{"TestShowSession_RendersArtifacts", _test.TestShowSession_RendersArtifacts},

	{"TestStats_WithMultipleErrorTypes", _test.TestStats_WithMultipleErrorTypes},

	{"TestListSessions_MetricsDisplayed", _test.TestListSessions_MetricsDisplayed},

	{"TestListDecisions_EmptyFile", _test.TestListDecisions_EmptyFile},

	{"TestListDecisions_MultipleDecisions", _test.TestListDecisions_MultipleDecisions},

	{"TestListDecisions_FilterByCategory", _test.TestListDecisions_FilterByCategory},

	{"TestListDecisions_FilterByImpact", _test.TestListDecisions_FilterByImpact},

	{"TestListDecisions_FilterBySince", _test.TestListDecisions_FilterBySince},

	{"TestListPreferences_EmptyFile", _test.TestListPreferences_EmptyFile},

	{"TestListPreferences_MultiplePreferences", _test.TestListPreferences_MultiplePreferences},

	{"TestListPreferences_FilterByCategory", _test.TestListPreferences_FilterByCategory},

	{"TestListPreferences_FilterByScope", _test.TestListPreferences_FilterByScope},

	{"TestShowPerformance_EmptyFile", _test.TestShowPerformance_EmptyFile},

	{"TestShowPerformance_MultipleMetrics", _test.TestShowPerformance_MultipleMetrics},

	{"TestShowPerformance_ByOperation", _test.TestShowPerformance_ByOperation},

	{"TestShowPerformance_SlowOnly", _test.TestShowPerformance_SlowOnly},

	{"TestShowPerformance_FilterBySince", _test.TestShowPerformance_FilterBySince},

	{"TestFormatBytes", _test.TestFormatBytes},

	{"TestPrintHelp_IncludesNewSubcommands", _test.TestPrintHelp_IncludesNewSubcommands},

	{"TestQueryDecisions_MissingFile", _test.TestQueryDecisions_MissingFile},

	{"TestQueryDecisions_WithLimit", _test.TestQueryDecisions_WithLimit},

	{"TestQueryPreferences_MissingFile", _test.TestQueryPreferences_MissingFile},

	{"TestQueryPreferences_WithLimit", _test.TestQueryPreferences_WithLimit},

	{"TestQueryPerformance_MissingFile", _test.TestQueryPerformance_MissingFile},

	{"TestQueryPerformance_WithFilters", _test.TestQueryPerformance_WithFilters},

	{"TestQueryPerformanceSummary", _test.TestQueryPerformanceSummary},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/Bucket-Chemist/GOgent-Fortress/cmd/gogent-archive"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

